language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_deploy:
  - rvm 1.9.3 do gem install mime-types -v 2.6.2
