language: ruby
rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - jruby-head
before_install:
  - gem update --system
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
